### ISSUE TITLE
Change repo organzation to Jekyll blog style

### ISSUE THREAD

**Issue by danieljsummers** [the-fsharp-mirror/the-fsharp-mirror.github.io#1]
(from a request on Slack)

Things we know currently need to be done:
* Move existing post to `_posts` directory

Other questions:
* Should the front page show all posts, be paginated, or just show the most recent?
* If paginated - how many per page?
* Do you want links to the "previous" and "next" posts at the top/bottom/both?
* URLs - `.html` or none?

That should be enough to make sure that I make the template so that, when you publish the next post, it'll look the way you'd like.

**Comment by tpetricek** [comment]
Regarding other questions:

> Should the front page show all posts, be paginated, or just show the most recent?

I'd say show full contents of the first 3 posts and then outlines of all other posts. We can add paging when we need to.

> Do you want links to the "previous" and "next" posts at the top/bottom/both?

I don't think so. I imagine people will mainly read things on the homepage only anyway.

> URLs - .html or none?

I'd go for URLs without `html`, but no strong opinion.
